services:
  - type: web
    name: petrolpump-backend
    runtime: docker
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RUb2tlbjEyMzQ1Njc4OTA=
      - key: JWT_EXPIRATION
        value: 86400000
